name: tests

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  tests:
    strategy:
      matrix:
        python: [3.9]
    runs-on: ubuntu-latest
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{matrix.python}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python}}
      - name: Install poppler
        run: sudo apt-get install -y poppler-utils
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: install metahtml
        run: |
          cd metahtml
          git init
          git remote add origin https://github.com/mikeizbicki/metahtml
          git config core.sparseCheckout true
          echo '/*' > .git/info/sparse-checkout
          echo '!/tests' >> .git/info/sparse-checkout
          git pull origin master
          pip install .
          cd ..
      # Disable doctest because non-deterministic
      # - name: run doctest
      #   run: |
      #     for i in {1..10}; do
      #       python -m doctest ragnews/__init__.py && break
      #     done
      - name: run query tests
        run: |
          python3 ragnews/__init__.py --query "Who is the current democratic presidential nominee?"
          python3 ragnews/__init__.py --query "What is the policy position of Trump related to illegal Mexican immigrants?"